name: Docker Build and Push to GHCR

on:
  workflow_dispatch:
    branches:
      - main
    paths:
      - '1.22.0/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: ~/.cache
          key: ${{ runner.os }}-build-${{ hashFiles('**/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Build and push Docker image
        run: |
          docker buildx build --platform linux/arm64 -t ghcr.io/${{ github.actor }}/unbound-cust:1.22.0 --push ./1.22.0
