name: Docker Build

on:
  workflow_dispatch:
    branches:
      - main # Adjust to the branch you want to trigger the build on
    paths:
      - '1.22.0/**' # Specify the directory or version you want to build from (like 1.22.0)
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
            path: ~/.cache
            key: ${{ runner.os }}-build-${{ hashFiles('**/Dockerfile') }}
            restore-keys: |
              ${{ runner.os }}-build-

      - name: Build Docker image
        run: |
          docker build -t unbound-cust:1.22.0 ./1.22.0 # Adjust to the directory where the Dockerfile is located


