name: Docker Build and Push to GHCR

on:
  workflow_dispatch:
    branches:
      - main
    paths:
      - '1.22.0/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: ~/.cache
          key: ${{ runner.os }}-build-${{ hashFiles('**/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Build Docker image
        run: |
          docker buildx build --platform linux/arm64 -t unbound-cust:1.22.0 ./1.22.0

      # Login to GitHub Container Registry (GHCR)
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}               # GitHub username
          password: ${{ secrets.GHCR_TOKEN }}         # GHCR token stored in secrets
          registry: ghcr.io                      # Specify the GHCR registry


      # Tag Docker image for GHCR
      - name: Tag Docker image for GHCR
        run: |
          docker tag unbound-cust:1.22.0 ghcr.io/${{ github.repository_owner }}/unbound-cust:1.22.0

      # Push the image to GHCR
      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/unbound-cust:1.22.0
